# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CC_Mainpage.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(675, 572)
        MainWindow.setDockNestingEnabled(True)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(190, 70, 271, 301))
        self.textEdit.setObjectName("textEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setAcceptDrops(True)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.menubar = PrintCoinList(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 675, 22))
        self.menubar.setObjectName("menubar")
        self.menuCoin_Calculator = QtWidgets.QMenu(self.menubar)
        self.menuCoin_Calculator.setObjectName("menuCoin_Calculator")
        self.menuMultiple_Coin = QtWidgets.QMenu(self.menubar)
        self.menuMultiple_Coin.setObjectName("menuMultiple_Coin")
        self.menuCalculator = QtWidgets.QMenu(self.menubar)
        self.menuCalculator.setObjectName("menuCalculator")
        self.menuPrint_Coin_List = QtWidgets.QMenu(self.menubar)
        self.menuPrint_Coin_List.setObjectName("menuPrint_Coin_List")
        self.menuSet_Details = QtWidgets.QMenu(self.menubar)
        self.menuSet_Details.setObjectName("menuSet_Details")
        self.menuQuit_Converter = QtWidgets.QMenu(self.menubar)
        self.menuQuit_Converter.setObjectName("menuQuit_Converter")
        MainWindow.setMenuBar(self.menubar)
        self.actionSet_Currency = QtWidgets.QAction(MainWindow)
        self.actionSet_Currency.setObjectName("actionSet_Currency")
        self.actionSet_minimum_coin_input_value = QtWidgets.QAction(MainWindow)
        self.actionSet_minimum_coin_input_value.setObjectName("actionSet_minimum_coin_input_value")
        self.actionSet_maxiumum_coin_input_value = QtWidgets.QAction(MainWindow)
        self.actionSet_maxiumum_coin_input_value.setObjectName("actionSet_maxiumum_coin_input_value")
        self.actionReturn_to_main_menu = QtWidgets.QAction(MainWindow)
        self.actionReturn_to_main_menu.setObjectName("actionReturn_to_main_menu")
        self.actionOpen = QtWidgets.QAction(MainWindow)
        self.actionOpen.setObjectName("actionOpen")
        self.actionClose = QtWidgets.QAction(MainWindow)
        self.actionClose.setObjectName("actionClose")
        self.actionOpen_2 = QtWidgets.QAction(MainWindow)
        self.actionOpen_2.setObjectName("actionOpen_2")
        self.actionClose_2 = QtWidgets.QAction(MainWindow)
        self.actionClose_2.setObjectName("actionClose_2")
        self.actionOpen_3 = QtWidgets.QAction(MainWindow)
        self.actionOpen_3.setObjectName("actionOpen_3")
        self.actionClose_3 = QtWidgets.QAction(MainWindow)
        self.actionClose_3.setObjectName("actionClose_3")
        self.actionOpen_4 = QtWidgets.QAction(MainWindow)
        self.actionOpen_4.setObjectName("actionOpen_4")
        self.actionClose_4 = QtWidgets.QAction(MainWindow)
        self.actionClose_4.setObjectName("actionClose_4")
        self.Quit = QtWidgets.QAction(MainWindow)
        self.Quit.setObjectName("Quit")
        self.menuCoin_Calculator.addAction(self.actionOpen)
        self.menuCoin_Calculator.addAction(self.actionClose)
        self.menuMultiple_Coin.addAction(self.actionOpen_2)
        self.menuMultiple_Coin.addAction(self.actionClose_2)
        self.menuCalculator.addAction(self.actionOpen_3)
        self.menuCalculator.addAction(self.actionClose_3)
        self.menuPrint_Coin_List.addAction(self.actionSet_Currency)
        self.menuPrint_Coin_List.addAction(self.actionSet_minimum_coin_input_value)
        self.menuPrint_Coin_List.addAction(self.actionSet_maxiumum_coin_input_value)
        self.menuPrint_Coin_List.addAction(self.actionReturn_to_main_menu)
        self.menuSet_Details.addAction(self.actionOpen_4)
        self.menuSet_Details.addAction(self.actionClose_4)
        self.menubar.addAction(self.menuCoin_Calculator.menuAction())
        self.menubar.addAction(self.menuMultiple_Coin.menuAction())
        self.menubar.addAction(self.menuCalculator.menuAction())
        self.menubar.addAction(self.menuPrint_Coin_List.menuAction())
        self.menubar.addAction(self.menuSet_Details.menuAction())
        self.menubar.addAction(self.menuQuit_Converter.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.textEdit.setHtml(_translate("MainWindow", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'.SF NS Text\'; font-size:13pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:18pt;\">Welcome to CAPSTONE 2 Converter.</span><br />This programme where you can convert your currency into USD and MGA. Select from the main menu bar. </p>\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\">Please use responsibly.</p></body></html>"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.menuCoin_Calculator.setTitle(_translate("MainWindow", "Coin Calculator"))
        self.menuMultiple_Coin.setTitle(_translate("MainWindow", "Multiple Coin"))
        self.menuCalculator.setTitle(_translate("MainWindow", "Calculator"))
        self.menuPrint_Coin_List.setTitle(_translate("MainWindow", "Print Coin List"))
        self.menuSet_Details.setTitle(_translate("MainWindow", "Set Details"))
        self.menuQuit_Converter.setTitle(_translate("MainWindow", "Quit Converter"))
        self.actionSet_Currency.setText(_translate("MainWindow", "Set Currency"))
        self.actionSet_minimum_coin_input_value.setText(_translate("MainWindow", "Set minimum coin input value"))
        self.actionSet_maxiumum_coin_input_value.setText(_translate("MainWindow", "Set maxiumum coin input value"))
        self.actionReturn_to_main_menu.setText(_translate("MainWindow", "Return to main menu"))
        self.actionOpen.setText(_translate("MainWindow", "Open"))
        self.actionClose.setText(_translate("MainWindow", "Close"))
        self.actionOpen_2.setText(_translate("MainWindow", "Open"))
        self.actionClose_2.setText(_translate("MainWindow", "Close"))
        self.actionOpen_3.setText(_translate("MainWindow", "Open"))
        self.actionClose_3.setText(_translate("MainWindow", "Close"))
        self.actionOpen_4.setText(_translate("MainWindow", "Open"))
        self.actionClose_4.setText(_translate("MainWindow", "Close"))
        self.Quit.setText(_translate("MainWindow", "Quit"))
from coinlist import PrintCoinList


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
