# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'CC_SETDETAILS.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(825, 772)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(190, 110, 101, 20))
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(340, 110, 181, 21))
        self.lineEdit.setObjectName("lineEdit")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(190, 160, 101, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(200, 210, 101, 20))
        self.label_3.setObjectName("label_3")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(340, 160, 181, 21))
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.radioButton = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton.setGeometry(QtCore.QRect(340, 210, 100, 20))
        self.radioButton.setObjectName("radioButton")
        self.radioButton_2 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_2.setGeometry(QtCore.QRect(400, 210, 100, 20))
        self.radioButton_2.setObjectName("radioButton_2")
        self.radioButton_3 = QtWidgets.QRadioButton(self.centralwidget)
        self.radioButton_3.setGeometry(QtCore.QRect(470, 210, 100, 20))
        self.radioButton_3.setObjectName("radioButton_3")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(310, 290, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(280, 360, 181, 101))
        self.label_4.setObjectName("label_4")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 825, 22))
        self.menubar.setObjectName("menubar")
        self.menuSet_Details = QtWidgets.QMenu(self.menubar)
        self.menuSet_Details.setObjectName("menuSet_Details")
        self.menuSet_minimum_coin_input_value = QtWidgets.QMenu(self.menubar)
        self.menuSet_minimum_coin_input_value.setObjectName("menuSet_minimum_coin_input_value")
        self.menuSet_maxiumum_coin_input_value = QtWidgets.QMenu(self.menubar)
        self.menuSet_maxiumum_coin_input_value.setObjectName("menuSet_maxiumum_coin_input_value")
        self.menuReturn_to_main_menu = QtWidgets.QMenu(self.menubar)
        self.menuReturn_to_main_menu.setObjectName("menuReturn_to_main_menu")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuSet_Details.menuAction())
        self.menubar.addAction(self.menuSet_minimum_coin_input_value.menuAction())
        self.menubar.addAction(self.menuSet_maxiumum_coin_input_value.menuAction())
        self.menubar.addAction(self.menuReturn_to_main_menu.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Minimum Value"))
        self.label_2.setText(_translate("MainWindow", "Maximum Values"))
        self.label_3.setText(_translate("MainWindow", "Set Currency"))
        self.radioButton.setText(_translate("MainWindow", "GBD"))
        self.radioButton_2.setText(_translate("MainWindow", "USD"))
        self.radioButton_3.setText(_translate("MainWindow", "MGA"))
        self.pushButton.setText(_translate("MainWindow", "CONFIRM"))
        self.label_4.setText(_translate("MainWindow", "Results"))
        self.menuSet_Details.setTitle(_translate("MainWindow", "Set Details"))
        self.menuSet_minimum_coin_input_value.setTitle(_translate("MainWindow", "Set minimum coin input value"))
        self.menuSet_maxiumum_coin_input_value.setTitle(_translate("MainWindow", "Set maxiumum coin input value"))
        self.menuReturn_to_main_menu.setTitle(_translate("MainWindow", "Return to main menu"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
