# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Justbuttons.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.CoinCalculatorbutton = QtWidgets.QPushButton(self.centralwidget)
        self.CoinCalculatorbutton.setGeometry(QtCore.QRect(30, 20, 121, 32))
        self.CoinCalculatorbutton.setObjectName("CoinCalculatorbutton")
        self.MultipleCoin_3button = QtWidgets.QPushButton(self.centralwidget)
        self.MultipleCoin_3button.setGeometry(QtCore.QRect(150, 20, 113, 32))
        self.MultipleCoin_3button.setObjectName("MultipleCoin_3button")
        self.Configurationsbutton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.Configurationsbutton_2.setGeometry(QtCore.QRect(270, 20, 113, 32))
        self.Configurationsbutton_2.setObjectName("Configurationsbutton_2")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(79, 79, 681, 401))
        self.stackedWidget.setObjectName("stackedWidget")
        self.CoinCalculatorPage = QtWidgets.QWidget()
        self.CoinCalculatorPage.setObjectName("CoinCalculatorPage")
        self.label = QtWidgets.QLabel(self.CoinCalculatorPage)
        self.label.setGeometry(QtCore.QRect(250, 70, 241, 16))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.CoinCalculatorPage)
        self.pushButton.setGeometry(QtCore.QRect(280, 160, 113, 32))
        self.pushButton.setObjectName("pushButton")
        self.stackedWidget.addWidget(self.CoinCalculatorPage)
        self.MultipeCoinPage = QtWidgets.QWidget()
        self.MultipeCoinPage.setObjectName("MultipeCoinPage")
        self.label_2 = QtWidgets.QLabel(self.MultipeCoinPage)
        self.label_2.setGeometry(QtCore.QRect(240, 70, 181, 20))
        self.label_2.setObjectName("label_2")
        self.pushButton_2 = QtWidgets.QPushButton(self.MultipeCoinPage)
        self.pushButton_2.setGeometry(QtCore.QRect(260, 190, 113, 32))
        self.pushButton_2.setObjectName("pushButton_2")
        self.stackedWidget.addWidget(self.MultipeCoinPage)
        self.Configurations = QtWidgets.QWidget()
        self.Configurations.setObjectName("Configurations")
        self.label_3 = QtWidgets.QLabel(self.Configurations)
        self.label_3.setGeometry(QtCore.QRect(260, 110, 151, 20))
        self.label_3.setObjectName("label_3")
        self.pushButton_3 = QtWidgets.QPushButton(self.Configurations)
        self.pushButton_3.setGeometry(QtCore.QRect(240, 180, 161, 71))
        self.pushButton_3.setObjectName("pushButton_3")
        self.stackedWidget.addWidget(self.Configurations)
        MainWindow.setCentralWidget(self.centralwidget)
        self.actionMenu2 = QtWidgets.QAction(MainWindow)
        self.actionMenu2.setObjectName("actionMenu2")

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.CoinCalculatorbutton.setText(_translate("MainWindow", "Coin Calculator"))
        self.MultipleCoin_3button.setText(_translate("MainWindow", "Multiple Coin"))
        self.Configurationsbutton_2.setText(_translate("MainWindow", "Configurations"))
        self.label.setText(_translate("MainWindow", "COIN CALCULATOR PAGE"))
        self.pushButton.setText(_translate("MainWindow", "PushButton"))
        self.label_2.setText(_translate("MainWindow", "MULTIPLE COIN PAGE "))
        self.pushButton_2.setText(_translate("MainWindow", "Multiple Coin Button"))
        self.label_3.setText(_translate("MainWindow", "Configuration Page"))
        self.pushButton_3.setText(_translate("MainWindow", "Configuration button"))
        self.actionMenu2.setText(_translate("MainWindow", "Menu2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
