# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Testing123.ui'
#
# Created by: PyQt5 UI code generator 5.15.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 500)
        MainWindow.setMinimumSize(QtCore.QSize(1000, 500))
        MainWindow.setStyleSheet("background-color: rgb(45, 45, 45);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Top_Bar = QtWidgets.QFrame(self.centralwidget)
        self.Top_Bar.setMaximumSize(QtCore.QSize(16777215, 40))
        self.Top_Bar.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.Top_Bar.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Top_Bar.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Top_Bar.setObjectName("Top_Bar")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.Top_Bar)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame_toggle = QtWidgets.QFrame(self.Top_Bar)
        self.frame_toggle.setMaximumSize(QtCore.QSize(70, 40))
        self.frame_toggle.setStyleSheet("background-color: rgb(85, 170, 255);")
        self.frame_toggle.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_toggle.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_toggle.setObjectName("frame_toggle")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_toggle)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Btn_Toggle = QtWidgets.QPushButton(self.frame_toggle)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.Btn_Toggle.sizePolicy().hasHeightForWidth())
        self.Btn_Toggle.setSizePolicy(sizePolicy)
        self.Btn_Toggle.setStyleSheet("color: rgb(255, 255, 255);\n"
"border: 0px solid;")
        self.Btn_Toggle.setObjectName("Btn_Toggle")
        self.verticalLayout_2.addWidget(self.Btn_Toggle)
        self.horizontalLayout.addWidget(self.frame_toggle)
        self.frame_top = QtWidgets.QFrame(self.Top_Bar)
        self.frame_top.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_top.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top.setObjectName("frame_top")
        self.horizontalLayout.addWidget(self.frame_top)
        self.verticalLayout.addWidget(self.Top_Bar)
        self.Content = QtWidgets.QFrame(self.centralwidget)
        self.Content.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Content.setFrameShadow(QtWidgets.QFrame.Raised)
        self.Content.setObjectName("Content")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.Content)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_left_menu = QtWidgets.QFrame(self.Content)
        self.frame_left_menu.setMinimumSize(QtCore.QSize(100, 0))
        self.frame_left_menu.setMaximumSize(QtCore.QSize(70, 16777215))
        self.frame_left_menu.setStyleSheet("background-color: rgb(35, 35, 35);")
        self.frame_left_menu.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left_menu.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left_menu.setObjectName("frame_left_menu")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.frame_left_menu)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.frame_top_menus = QtWidgets.QFrame(self.frame_left_menu)
        self.frame_top_menus.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.frame_top_menus.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_top_menus.setObjectName("frame_top_menus")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.frame_top_menus)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.CoinCalculator = QtWidgets.QPushButton(self.frame_top_menus)
        self.CoinCalculator.setMinimumSize(QtCore.QSize(0, 40))
        self.CoinCalculator.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.CoinCalculator.setObjectName("CoinCalculator")
        self.verticalLayout_4.addWidget(self.CoinCalculator)
        self.MultipleCoin = QtWidgets.QPushButton(self.frame_top_menus)
        self.MultipleCoin.setMinimumSize(QtCore.QSize(0, 40))
        self.MultipleCoin.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.MultipleCoin.setObjectName("MultipleCoin")
        self.verticalLayout_4.addWidget(self.MultipleCoin)
        self.Calculator = QtWidgets.QPushButton(self.frame_top_menus)
        self.Calculator.setMinimumSize(QtCore.QSize(0, 40))
        self.Calculator.setStyleSheet("QPushButton {\n"
"    color: rgb(255, 255, 255);\n"
"    background-color: rgb(35, 35, 35);\n"
"    border: 0px solid;\n"
"}\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}")
        self.Calculator.setObjectName("Calculator")
        self.verticalLayout_4.addWidget(self.Calculator)
        self.verticalLayout_3.addWidget(self.frame_top_menus, 0, QtCore.Qt.AlignTop)
        self.horizontalLayout_2.addWidget(self.frame_left_menu)
        self.frame_pages = QtWidgets.QFrame(self.Content)
        self.frame_pages.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_pages.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_pages.setObjectName("frame_pages")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.frame_pages)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.stackedWidget = QtWidgets.QStackedWidget(self.frame_pages)
        self.stackedWidget.setObjectName("stackedWidget")
        self.Coin_Calculator = QtWidgets.QWidget()
        self.Coin_Calculator.setObjectName("Coin_Calculator")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.Coin_Calculator)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_Coin_Calculator = QtWidgets.QLabel(self.Coin_Calculator)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_Coin_Calculator.setFont(font)
        self.label_Coin_Calculator.setStyleSheet("color: #FFFFFF; ")
        self.label_Coin_Calculator.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Coin_Calculator.setObjectName("label_Coin_Calculator")
        self.verticalLayout_6.addWidget(self.label_Coin_Calculator)
        self.stackedWidget.addWidget(self.Coin_Calculator)
        self.Multiple_Coin = QtWidgets.QWidget()
        self.Multiple_Coin.setObjectName("Multiple_Coin")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.Multiple_Coin)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_Multiple_Coin = QtWidgets.QLabel(self.Multiple_Coin)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_Multiple_Coin.setFont(font)
        self.label_Multiple_Coin.setStyleSheet("color: #FFFFFF; ")
        self.label_Multiple_Coin.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Multiple_Coin.setObjectName("label_Multiple_Coin")
        self.verticalLayout_7.addWidget(self.label_Multiple_Coin)
        self.stackedWidget.addWidget(self.Multiple_Coin)
        self.Calculator_2 = QtWidgets.QWidget()
        self.Calculator_2.setObjectName("Calculator_2")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.Calculator_2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_Multiple_Coin_2 = QtWidgets.QLabel(self.Calculator_2)
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_Multiple_Coin_2.setFont(font)
        self.label_Multiple_Coin_2.setStyleSheet("color: #FFFFFF; ")
        self.label_Multiple_Coin_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Multiple_Coin_2.setObjectName("label_Multiple_Coin_2")
        self.verticalLayout_8.addWidget(self.label_Multiple_Coin_2)
        self.stackedWidget.addWidget(self.Calculator_2)
        self.Print_Coin = QtWidgets.QWidget()
        self.Print_Coin.setObjectName("Print_Coin")
        self.stackedWidget.addWidget(self.Print_Coin)
        self.verticalLayout_5.addWidget(self.stackedWidget)
        self.horizontalLayout_2.addWidget(self.frame_pages)
        self.verticalLayout.addWidget(self.Content)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(3)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.Btn_Toggle.setText(_translate("MainWindow", "TOGGLE"))
        self.CoinCalculator.setText(_translate("MainWindow", "Coin Calculator"))
        self.MultipleCoin.setText(_translate("MainWindow", "Multiple Coin"))
        self.Calculator.setText(_translate("MainWindow", "Calculator"))
        self.label_Coin_Calculator.setText(_translate("MainWindow", "COIN CALCULATOR"))
        self.label_Multiple_Coin.setText(_translate("MainWindow", "MULTIPLE COIN"))
        self.label_Multiple_Coin_2.setText(_translate("MainWindow", "CALCULATOR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
